/** @type {import('tailwindcss').Config} */
const plugin = require('tailwindcss/plugin')
const defaultTheme = require('tailwindcss/defaultTheme')
const colors = require('tailwindcss/colors')

module.exports = {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/**/*.blade.php',
        './vendor/filament/**/*.blade.php',
    ],
    safelist: [
        'grid-cols-[70px,repeat(6,200px)]',
        'grid-cols-[70px,repeat(7,200px)]',
        'grid-cols-[70px,repeat(8,200px)]',
        'grid-cols-[70px,repeat(9,200px)]',
        'grid-cols-[70px,repeat(10,200px)]',
        'grid-cols-[70px,repeat(11,200px)]',
        'grid-cols-[70px,repeat(12,200px)]',
        'row-span-1',
        'row-span-2',
        'row-span-3',
        'row-span-4',
        'row-span-5',
        'row-span-6',
        'row-span-7',
        'row-span-8',
        'row-span-9',
        'row-span-10',
        'row-span-11',
        'row-span-12',
        'row-span-13',
        'row-span-14',
        'row-span-15',
        'row-span-16',
        'row-span-17',
        'row-span-18',
        'row-span-19',
        'row-span-20',
        'row-span-21',
        'row-span-22',
        'row-span-23',
        'row-span-24',
        'row-span-25',
        'row-span-26',
        'row-span-27',
        'row-span-28',
        'row-span-29',
        'row-span-30',
        'row-span-31',
        'row-span-32',
        'row-span-33',
        'row-span-34',
        'row-span-35',
        'row-span-36',
        'row-span-37',
        'row-span-38',
        'row-span-39',
        'row-span-40',
        'row-span-41',
        'row-span-42',
        'row-span-43',
        'row-span-44',
        'row-start-1',
        'row-start-2',
        'row-start-3',
        'row-start-4',
        'row-start-5',
        'row-start-6',
        'row-start-7',
        'row-start-8',
        'row-start-9',
        'row-start-10',
        'row-start-11',
        'row-start-12',
        'row-start-13',
        'row-start-14',
        'row-start-15',
        'row-start-16',
        'row-start-17',
        'row-start-18',
        'row-start-19',
        'row-start-20',
        'row-start-21',
        'row-start-22',
        'row-start-23',
        'row-start-24',
        'row-start-25',
        'row-start-26',
        'row-start-27',
        'row-start-28',
        'row-start-29',
        'row-start-30',
        'row-start-31',
        'row-start-32',
        'row-start-33',
        'row-start-34',
        'row-start-35',
        'row-start-36',
        'row-start-37',
        'row-start-38',
        'row-start-39',
        'row-start-40',
        'row-start-41',
        'row-start-42',
        'row-start-43',
        'row-start-44',
        'col-start-1',
        'col-start-2',
        'col-start-3',
        'col-start-4',
        'col-start-5',
        'col-start-6',
        'col-start-7',
        'col-start-8',
        'col-start-9',
        'col-start-10',
        'col-start-11',
        'col-start-12',
        'col-start-13',
        'col-start-14',
        'col-start-15',
        'col-start-16',
        'col-start-17',
        'col-start-18',
        'col-start-19',
        'col-start-20',
        'col-start-21',
        'col-start-22',
        'col-start-23',
        'col-start-24',
        'col-start-25',
        'col-start-26',
        'col-start-27',
        'col-start-28',
        'col-start-29',
        'col-start-30',
        'col-start-31',
        'col-start-32',
        'col-start-33',
        'col-start-34',
        'col-start-35',
        'col-start-36',
        'col-start-37',
        'col-start-38',
        'col-start-39',
        'col-start-40',
        'col-start-41',
        'col-start-42',
        'col-start-43',
        'col-start-44'
    ],
    darkMode: "class",
    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                handwriting: ['Cookie', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                'bunababy-50': '#FCE7F3',
                'bunababy-100': '#FE70C5',
                'bunababy-200': '#FE0E9C',
                'bunababy-300': '#D7A4DF',
                'bunababy-400': '#B95CC7',
                'bunababy-500': '#D9969D',
                'bunababy-600': '#A5586A',
                danger: colors.rose,
                primary: colors.blue,
                success: colors.green,
                warning: colors.yellow,
            },
            maxWidth: {
                '8xl': '90rem',
                '9xl': '105rem',
                '10xl': '120rem',
            },
            zIndex: {
                '1': 1,
                '60': 60,
                '70': 70,
                '80': 80,
                '90': 90,
                '100': 100,
            },
            typography: {
                DEFAULT: {
                css: {
                    a: {
                    textDecoration: 'none',
                    '&:hover': {
                        opacity: '.75',
                    },
                    },
                    img: {
                    borderRadius: defaultTheme.borderRadius.lg,
                    },
                },
                },
            },
            gridRow: {
                'span-7': 'span 7 / span 7',
                'span-8': 'span 8 / span 8',
                'span-9': 'span 9 / span 9',
                'span-10': 'span 10 / span 10',
                'span-11': 'span 11 / span 11',
                'span-12': 'span 12 / span 12',
                'span-13': 'span 13 / span 13',
                'span-14': 'span 14 / span 14',
                'span-15': 'span 15 / span 15',
                'span-16': 'span 16 / span 16',
                'span-17': 'span 17 / span 17',
                'span-18': 'span 18 / span 18',
                'span-19': 'span 19 / span 19',
                'span-20': 'span 20 / span 20',
                'span-21': 'span 21 / span 21',
                'span-22': 'span 22 / span 22',
                'span-23': 'span 23 / span 23',
                'span-24': 'span 24 / span 24',
                'span-25': 'span 25 / span 25',
                'span-26': 'span 26 / span 26',
                'span-27': 'span 27 / span 27',
                'span-28': 'span 28 / span 28',
                'span-29': 'span 29 / span 29',
                'span-30': 'span 30 / span 30',
                'span-31': 'span 31 / span 31',
                'span-32': 'span 32 / span 32',
                'span-33': 'span 33 / span 33',
                'span-34': 'span 34 / span 34',
                'span-35': 'span 35 / span 35',
                'span-36': 'span 36 / span 36',
                'span-37': 'span 37 / span 37',
                'span-38': 'span 38 / span 38',
                'span-39': 'span 39 / span 39',
                'span-40': 'span 40 / span 40',
                'span-41': 'span 41 / span 41',
                'span-42': 'span 42 / span 42',
                'span-43': 'span 43 / span 43',
                'span-44': 'span 44 / span 44',
            },
            gridRowStart: {
                '8': '8',
                '9': '9',
                '10': '10',
                '11': '11',
                '12': '12',
                '13': '13',
                '14': '14',
                '15': '15',
                '16': '16',
                '17': '17',
                '18': '18',
                '19': '19',
                '20': '20',
                '21': '21',
                '22': '22',
                '23': '23',
                '24': '24',
                '25': '25',
                '26': '26',
                '27': '27',
                '28': '28',
                '29': '29',
                '30': '30',
                '31': '31',
                '32': '32',
                '33': '33',
                '34': '34',
                '35': '35',
                '36': '36',
                '37': '37',
                '38': '38',
                '39': '39',
                '40': '40',
                '41': '41',
                '42': '42',
                '43': '43',
                '44': '44',
            },
            gridColumnStart: {
                '13': '13',
                '14': '14',
                '15': '15',
                '16': '16',
                '17': '17',
                '18': '18',
                '19': '19',
                '20': '20',
                '21': '21',
                '22': '22',
                '23': '23',
                '24': '24',
                '25': '25',
                '26': '26',
                '27': '27',
                '28': '28',
                '29': '29',
                '30': '30',
                '31': '31',
                '32': '32',
                '33': '33',
                '34': '34',
                '35': '35',
                '36': '36',
                '37': '37',
                '38': '38',
                '39': '39',
                '40': '40',
                '41': '41',
                '42': '42',
                '43': '43',
                '44': '44',
            }
        },
    },

    plugins: [
        // require('@tailwindcss/aspect-ratio'),
        require('@tailwindcss/forms'),
        // require('@tailwindcss/typography'),
        plugin(function({ addUtilities }) {
            const utilFormSwitch = {
                '.form-switch': {
                'border': 'transparent',
                'background-color': colors.gray[300],
                'background-image': "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='-4 -4 8 8'%3e%3ccircle r='3' fill='%23fff'/%3e%3c/svg%3e\")",
                'background-position': 'left center',
                'background-repeat': 'no-repeat',
                'background-size': 'contain !important',
                'vertical-align': 'top',
                '&:checked': {
                    'border': 'transparent',
                    'background-color': 'currentColor',
                    'background-image': "url(\"data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='-4 -4 8 8'%3e%3ccircle r='3' fill='%23fff'/%3e%3c/svg%3e\")",
                    'background-position': 'right center',
                },
                '&:disabled, &:disabled + label': {
                    'opacity': '.5',
                    'cursor': 'not-allowed',
                },
                },
            }

            addUtilities(utilFormSwitch)
        }),
    ],
};
